#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md", ".idea"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################


### Google Analytics ###
google_analytics: G-QNB5PNBM5B

# This is your site title
title: El Truckito
# Website language
lang: en-US
# Header Title
header-title: Overlanding the <strong>Americas</strong>
# Header Tagline
headter-tagline: Currently on <strong>stage 1</strong>

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com


####################################
######  Global Social Links   ######
####################################
socials:
  instagram: "ElTruckito"
  facebook: "ElTruckito"

#########################
######   Widgets   ######
#########################


# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME


#####################################
#############   Follow   ############
#####################################
follow-title: Follow Us

#####################################
############  Media  ############
#####################################
media-title: In Media
media-description: Listed, read, and watch about El Truckito
#
# Media Grid
#
media-categories:
  [Podcasts]
#  [Podcasts, Magazines, TV, Radio]
media:
#   Media Item
  - title: Svět je CooL
    categories: [Podcasts]
    image: svet_je_cool.jpeg
    url: "https://svetjecool.cz/el-truckito-na-ceste-kolem-sveta-v-truck-camperu/"
#   Media Item
  - title: The Small Truck Campers Show
    categories: [Podcasts]
    image: small_truck_campers.jpeg
    url: "https://open.spotify.com/episode/27eFdeKCA9RtSZn9Uhz12y?si=edb582e1785448e9"

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description:


#
# Team Members
#
team:
  # Team Member
  - name: Martin
    tagline: "Tech Alpinist: Aspiring mountaineer crafting world-transforming solutions. Explore further at <a href=\"https://www.martinkysel.com\">www.martinkysel.com.</a>"
    avatar: martin.jpg

  # Team Member
  - name: Amy
    tagline: "Content Sorceress: Conjuring digital word and video from the void. Must pet all cats. <a href=\"https://www.amyfoxwriter.com\">www.amyfoxwriter.com.</a>"
    avatar: amy.jpg

  # Team Member
  - name: El Truckito
    tagline: GMC Sierra 2500 HD, 2016 model. Absolute unit. 6.0L engine, can tow a bus. Incredibly sexy.
             Palomino Backpack Camper, 2016 model. Comes with the world’s comfiest bed and questionable placement of
             electrical outlets.
    avatar: truckito.jpg


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.

#####################################
#############   Footer   ############
#####################################
footer-header: FOLLOW OUR JOURNEY
footer-description: We are active on these social media platforms
footer-copyright-text: mkysel
footer-copyright-url: https://github.com/mkysel
footer-copyright-year: 2023
